/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gf.moto;

import com.gf.automovil.*;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author cissanal
 */
public class GUI_Moto extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Moto
     */
    public Moto a1 = new Moto("12345678A", 300, 20);
    public GUI_Moto(Moto a) {
        initComponents();
        this.jButtonAcelerar.setEnabled(false);
        this.jButtonDecelerar.setEnabled(false);
        this.jButtonParar.setEnabled(false);
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        int x = a.getVelocidadMax();
//        Automovil a1 = new Automovil(a.getMatricula(), a.getCapacidad(), a.getVelocidadMax(), a.getCapacidadDeposito());
        a1.setMatricula(a.getMatricula());
        a1.setCapacidad(a.getCapacidad());
        a1.setVelocidadMax(a.getVelocidadMax());
        a1.setCapacidadDeposito(a.getCapacidadDeposito());
        Icon icon = new ImageIcon(this.getClass().getResource("vacio.gif"));
        this.jLabelGif.setIcon(icon);
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonArrancar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jButtonRepostar = new javax.swing.JButton();
        jButtonAcelerar = new javax.swing.JButton();
        jButtonDecelerar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelDatos = new javax.swing.JLabel();
        jLabelGif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonArrancar.setText("Arrancar");
        jButtonArrancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArrancarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonArrancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 83, -1));

        jButtonParar.setText("Parar");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 79, -1));

        jButtonRepostar.setText("Repostar");
        jButtonRepostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepostarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRepostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 610, -1, 50));

        jButtonAcelerar.setText("Acelerar");
        jButtonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 81, 91));

        jButtonDecelerar.setText("Decelerar");
        jButtonDecelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecelerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDecelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, 50));

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, 79, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 79, -1));

        jLabelDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelDatosPropertyChange(evt);
            }
        });
        getContentPane().add(jLabelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 660, 420, 56));
        getContentPane().add(jLabelGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 780, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArrancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArrancarActionPerformed
        this.jButtonAcelerar.setEnabled(true);
        this.jButtonDecelerar.setEnabled(true);
        this.jButtonParar.setEnabled(true);
        this.jButtonArrancar.setEnabled(false);
        a1.Arrancar();
        this.jLabelDatos.setText(a1.toString());
        
    }//GEN-LAST:event_jButtonArrancarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        this.jButtonAcelerar.setEnabled(false);
        this.jButtonDecelerar.setEnabled(false);
        this.jButtonParar.setEnabled(false);
        this.jButtonArrancar.setEnabled(true);
        a1.Parar();
        this.jLabelDatos.setText(a1.toString());
        Icon icon = new ImageIcon(this.getClass().getResource("parado.gif"));
        this.jLabelGif.setIcon(icon);
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        a1.Entrar();
        this.jLabelDatos.setText(a1.toString());
        if(a1.getVelocidad()==0){
            Icon icon = new ImageIcon(this.getClass().getResource("parado.gif"));
        this.jLabelGif.setIcon(icon);
        }
        
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarActionPerformed
        a1.Acelerar();
        this.jLabelDatos.setText(a1.toString());
        Icon Normal = new ImageIcon(this.getClass().getResource("normal1.gif"));
        Icon Fast = new ImageIcon(this.getClass().getResource("fast.gif"));
        Icon VFast = new ImageIcon(this.getClass().getResource("veryfast.gif"));
        Icon SFast = new ImageIcon(this.getClass().getResource("superfast.gif"));
        Icon Crash = new ImageIcon(this.getClass().getResource("crash.gif"));
        
        if(a1.getVelocidad()>0&&a1.getVelocidad()<30){
            this.jLabelGif.setIcon(Normal);
        }
        if(a1.getVelocidad()>30&&a1.getVelocidad()<60){
            this.jLabelGif.setIcon(Fast);
        }
        if(a1.getVelocidad()>60&&a1.getVelocidad()<90){
            this.jLabelGif.setIcon(VFast);
        }
        if(a1.getVelocidad()>90){
            this.jLabelGif.setIcon(SFast);
        }
        if(a1.getVelocidad()>160){
            Random r1 = new Random();
            while(a1.getVelocidad()>160){
                
                int ran1 = r1.nextInt(10000);
                if(ran1>9990){
                    this.jLabelGif.setIcon(Crash);
                    a1.Parar();
                }
            }
        }
        
        
        
    }//GEN-LAST:event_jButtonAcelerarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        a1.Salir();
        this.jLabelDatos.setText(a1.toString());
        if(a1.getVelocidad()==0){
            Icon icon = new ImageIcon(this.getClass().getResource("vacio.gif"));
        this.jLabelGif.setIcon(icon);
        }
        
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonDecelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecelerarActionPerformed
        a1.Decelerar();
        this.jLabelDatos.setText(a1.toString());
        
        Icon Camry = new ImageIcon(this.getClass().getResource("parado.gif"));
        Icon Normal = new ImageIcon(this.getClass().getResource("normal1.gif"));
        Icon Fast = new ImageIcon(this.getClass().getResource("fast.gif"));
        Icon VFast = new ImageIcon(this.getClass().getResource("veryfast.gif"));
        Icon SFast = new ImageIcon(this.getClass().getResource("superfast.gif"));
        
        if(a1.getVelocidad()<=0){
            this.jLabelGif.setIcon(Camry);
        }
        if(a1.getVelocidad()>0&&a1.getVelocidad()<30){
            this.jLabelGif.setIcon(Normal);
        }
        if(a1.getVelocidad()>30&&a1.getVelocidad()<60){
            this.jLabelGif.setIcon(Fast);
        }
        if(a1.getVelocidad()>60&&a1.getVelocidad()<90){
            this.jLabelGif.setIcon(VFast);
        }
        if(a1.getVelocidad()>90){
            this.jLabelGif.setIcon(SFast);
        }
        
    }//GEN-LAST:event_jButtonDecelerarActionPerformed

    private void jButtonRepostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepostarActionPerformed
        a1.Repostar();
        this.jLabelDatos.setText(a1.toString());
        if(a1.getVelocidad()==0){
            Icon icon = new ImageIcon(this.getClass().getResource("refuel.gif"));
        this.jLabelGif.setIcon(icon);
        }
        
    }//GEN-LAST:event_jButtonRepostarActionPerformed

    private void jLabelDatosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelDatosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelDatosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Moto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUI_Automovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcelerar;
    private javax.swing.JButton jButtonArrancar;
    private javax.swing.JButton jButtonDecelerar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonRepostar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JLabel jLabelGif;
    // End of variables declaration//GEN-END:variables
}
