/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gf.gui.figuras;

import java.awt.Color;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author cissanal
 */
public class GUI_main extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Principal
     */
    private Color defaultColor = Color.BLUE;
    private Color selectedColor;
    private int outlineWidth = 1;//valores por defecto
    private boolean fill = false;

    public GUI_main() {
        initComponents();
        this.setTitle("Figuras Geometricas");
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.jRadioButtonDefault.setSelected(true);
        this.jRadioButtonDefault.setToolTipText("Black, outline width 1");
        this.jButtonColor.setEnabled(false);
        this.jSpinnerOutline.setEnabled(false);
        this.jCheckBoxFill.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupFormat = new javax.swing.ButtonGroup();
        jPanelFormato = new javax.swing.JPanel();
        jRadioButtonDefault = new javax.swing.JRadioButton();
        jRadioButtonCustomize = new javax.swing.JRadioButton();
        jCheckBoxFill = new javax.swing.JCheckBox();
        jLabelOutlineWidth = new javax.swing.JLabel();
        jButtonColor = new javax.swing.JButton();
        jSpinnerOutline = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDibujar = new javax.swing.JMenu();
        jMenuItemCirculo = new javax.swing.JMenuItem();
        jMenuItemRectangulo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFormato.setBorder(javax.swing.BorderFactory.createTitledBorder("Formato"));

        buttonGroupFormat.add(jRadioButtonDefault);
        jRadioButtonDefault.setSelected(true);
        jRadioButtonDefault.setText("Default");
        jRadioButtonDefault.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonDefaultStateChanged(evt);
            }
        });

        buttonGroupFormat.add(jRadioButtonCustomize);
        jRadioButtonCustomize.setText("Customize");
        jRadioButtonCustomize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomizeActionPerformed(evt);
            }
        });

        jCheckBoxFill.setText("Fill");
        jCheckBoxFill.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBoxFillStateChanged(evt);
            }
        });

        jLabelOutlineWidth.setText("Outline Width");

        jButtonColor.setText("Color");
        jButtonColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColorActionPerformed(evt);
            }
        });

        jSpinnerOutline.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        jSpinnerOutline.setToolTipText("Min:1 -  Max:100");
        jSpinnerOutline.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerOutlineStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormatoLayout = new javax.swing.GroupLayout(jPanelFormato);
        jPanelFormato.setLayout(jPanelFormatoLayout);
        jPanelFormatoLayout.setHorizontalGroup(
            jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoLayout.createSequentialGroup()
                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormatoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonDefault)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFormatoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonColor)
                        .addGap(15, 15, 15)))
                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelOutlineWidth)
                    .addComponent(jRadioButtonCustomize))
                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFormatoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jCheckBoxFill))
                    .addGroup(jPanelFormatoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSpinnerOutline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanelFormatoLayout.setVerticalGroup(
            jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonDefault)
                    .addComponent(jRadioButtonCustomize)
                    .addComponent(jCheckBoxFill))
                .addGap(18, 18, 18)
                .addGroup(jPanelFormatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOutlineWidth)
                    .addComponent(jButtonColor)
                    .addComponent(jSpinnerOutline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jMenuDibujar.setText("Dibujar");

        jMenuItemCirculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemCirculo.setText("Circulo");
        jMenuItemCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCirculoActionPerformed(evt);
            }
        });
        jMenuDibujar.add(jMenuItemCirculo);

        jMenuItemRectangulo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        jMenuItemRectangulo.setText("Rectangulo");
        jMenuItemRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRectanguloActionPerformed(evt);
            }
        });
        jMenuDibujar.add(jMenuItemRectangulo);

        jMenuBar1.add(jMenuDibujar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCirculoActionPerformed
        String input = JOptionPane.showInputDialog("Enter radius: ");
        if (input != null && !input.isEmpty()) {
            //tengo un radio 

            try {
                int radius = Integer.parseInt(input);

                if (radius > 0) {
                    Circulo c = new Circulo(radius, this.selectedColor, this.fill, this.outlineWidth);
                    GUI_canvas canvas = new GUI_canvas(c);
                    canvas.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "radius value not allowed", "Radius Error", JOptionPane.ERROR_MESSAGE);

                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "radius value not allowed", "Radius Error", JOptionPane.ERROR_MESSAGE);
            }
            //si ha salido bien, radio es numerico

        } else {
            JOptionPane.showMessageDialog(this, "You did not set a radius value", "Radius Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_jMenuItemCirculoActionPerformed

    private void jRadioButtonCustomizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCustomizeActionPerformed

    private void jRadioButtonDefaultStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonDefaultStateChanged
        if (jRadioButtonDefault.isSelected()) {
            this.jButtonColor.setEnabled(false);
            this.jSpinnerOutline.setEnabled(false);
            this.jCheckBoxFill.setEnabled(false);
        } else {
            this.jButtonColor.setEnabled(true);
            this.jSpinnerOutline.setEnabled(true);
            this.jCheckBoxFill.setEnabled(true);
        }

    }//GEN-LAST:event_jRadioButtonDefaultStateChanged

    private void jButtonColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColorActionPerformed
        this.selectedColor = JColorChooser.showDialog(this, "Choose a color for your shape", Color.blue);
        if (selectedColor != null) {
            this.jButtonColor.setBackground(selectedColor);
        }
        if (selectedColor == defaultColor) {
            this.jButtonColor.setBackground(null);
        }
    }//GEN-LAST:event_jButtonColorActionPerformed

    private void jSpinnerOutlineStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerOutlineStateChanged
        this.outlineWidth = Integer.parseInt(jSpinnerOutline.getValue().toString());
        System.out.println(outlineWidth);
    }//GEN-LAST:event_jSpinnerOutlineStateChanged

    private void jCheckBoxFillStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBoxFillStateChanged
        if (this.jCheckBoxFill.isSelected()) {
            this.fill = true;
        } else {
            this.fill = false;
        }
    }//GEN-LAST:event_jCheckBoxFillStateChanged

    private void jMenuItemRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRectanguloActionPerformed
        String inputW = JOptionPane.showInputDialog("Enter width: ");
        String inputH = JOptionPane.showInputDialog("Enter height: ");
        if ((inputW != null && !inputW.isEmpty())&&(inputH != null && !inputH.isEmpty())) {
             

            try {
                int width = Integer.parseInt(inputW);
                int height = Integer.parseInt(inputH);

                if (width > 0&&height>0) {
                    Rectangulo r = new Rectangulo(width, height, this.selectedColor, this.fill, this.outlineWidth);
                    GUI_canvas canvas = new GUI_canvas(r);
                    canvas.setVisible(true);

                } else {
                    JOptionPane.showMessageDialog(this, "Height or width values not allowed", "H/W Error", JOptionPane.ERROR_MESSAGE);

                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Height or width values not allowed", "H/W Error", JOptionPane.ERROR_MESSAGE);
            }
            

        } else {
            JOptionPane.showMessageDialog(this, "You did not set the height or width values", "H/W Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemRectanguloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new GUI_main().setVisible(true);
                GUI_main main = new GUI_main();
                main.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupFormat;
    private javax.swing.JButton jButtonColor;
    private javax.swing.JCheckBox jCheckBoxFill;
    private javax.swing.JLabel jLabelOutlineWidth;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDibujar;
    private javax.swing.JMenuItem jMenuItemCirculo;
    private javax.swing.JMenuItem jMenuItemRectangulo;
    private javax.swing.JPanel jPanelFormato;
    private javax.swing.JRadioButton jRadioButtonCustomize;
    private javax.swing.JRadioButton jRadioButtonDefault;
    private javax.swing.JSpinner jSpinnerOutline;
    // End of variables declaration//GEN-END:variables
}
