/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gf.banco;

/**
 *
 * @author cissanal
 */
public class Banco_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Banco_GUI
     */
    public Banco_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinnerNumCliente = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelDatosCuenta = new javax.swing.JLabel();
        jLabelDatosCliente = new javax.swing.JLabel();
        jButtonIntereses = new javax.swing.JButton();
        jButtonIngresar = new javax.swing.JButton();
        jButtonReintegrar = new javax.swing.JButton();
        jTextFieldReintegrar = new javax.swing.JTextField();
        jButtonIntereses1 = new javax.swing.JButton();
        jTextFieldIngresar1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonSeleccionarNumCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSpinnerNumCliente.setModel(new javax.swing.SpinnerNumberModel());
        jSpinnerNumCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jSpinnerNumCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 61, 50, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 421, 10));

        jLabelDatosCuenta.setText("Datos Cuenta:");
        getContentPane().add(jLabelDatosCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 370, -1));

        jLabelDatosCliente.setText("Datos Cliente:");
        getContentPane().add(jLabelDatosCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 370, -1));

        jButtonIntereses.setText("Intereses");
        getContentPane().add(jButtonIntereses, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jButtonIngresar.setText("Ingresar");
        getContentPane().add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jButtonReintegrar.setText("Reintegrar");
        getContentPane().add(jButtonReintegrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jTextFieldReintegrar.setText("Euros");
        getContentPane().add(jTextFieldReintegrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, -1));

        jButtonIntereses1.setText("Intereses");
        getContentPane().add(jButtonIntereses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, -1));

        jTextFieldIngresar1.setText("Euros");
        getContentPane().add(jTextFieldIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 80, -1));

        jButtonSeleccionarNumCliente.setText("Seleccionar Num Cliente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jButtonSeleccionarNumCliente)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSeleccionarNumCliente)
                .addContainerGap(266, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banco_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banco_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banco_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banco_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banco_GUI().setVisible(true);
            }
        });
        
        
        Cliente c1=new Cliente("ASDFGH434", "Pepe Ga");
        CuentaBancaria cuenta1 =new CuentaBancaria(493545, c1);
        c1.setCuentaBancaria(cuenta1);
        
    }
    
    
        
        
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonIntereses;
    private javax.swing.JButton jButtonIntereses1;
    private javax.swing.JButton jButtonReintegrar;
    private javax.swing.JButton jButtonSeleccionarNumCliente;
    private javax.swing.JLabel jLabelDatosCliente;
    private javax.swing.JLabel jLabelDatosCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerNumCliente;
    private javax.swing.JTextField jTextFieldIngresar1;
    private javax.swing.JTextField jTextFieldReintegrar;
    // End of variables declaration//GEN-END:variables
}
