/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gf.automovil;

/**
 *
 * @author cissanal
 */
public class GUI_Automovil extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Automovil
     */
    public Automovil a1 = new Automovil("12345678A", 5, 300, 20);
    public GUI_Automovil(Automovil a) {
        initComponents();
        this.jButtonAcelerar.setEnabled(false);
        this.jButtonDecelerar.setEnabled(false);
        this.jButtonParar.setEnabled(false);
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        int x = a.getVelocidadMax();
//        Automovil a1 = new Automovil(a.getMatricula(), a.getCapacidad(), a.getVelocidadMax(), a.getCapacidadDeposito());
        a1.setMatricula(a.getMatricula());
        a1.setCapacidad(a.getCapacidad());
        a1.setVelocidadMax(a.getVelocidadMax());
        a1.setCapacidadDeposito(a.getCapacidadDeposito());
        
    }
    
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonArrancar = new javax.swing.JButton();
        jButtonParar = new javax.swing.JButton();
        jButtonRepostar = new javax.swing.JButton();
        jButtonAcelerar = new javax.swing.JButton();
        jButtonDecelerar = new javax.swing.JButton();
        jButtonEntrar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonArrancar.setText("Arrancar");
        jButtonArrancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonArrancarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonArrancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 24, 83, -1));

        jButtonParar.setText("Parar");
        jButtonParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPararActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 24, 79, -1));

        jButtonRepostar.setText("Repostar");
        jButtonRepostar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepostarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRepostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 179, -1, 50));

        jButtonAcelerar.setText("Acelerar");
        jButtonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcelerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAcelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 70, 81, 91));

        jButtonDecelerar.setText("Decelerar");
        jButtonDecelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDecelerarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDecelerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 179, -1, 50));

        jButtonEntrar.setText("Entrar");
        jButtonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 70, 79, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 138, 79, -1));

        jLabelDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDatos.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jLabelDatosPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addComponent(jLabelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonArrancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonArrancarActionPerformed
        this.jButtonAcelerar.setEnabled(true);
        this.jButtonDecelerar.setEnabled(true);
        this.jButtonParar.setEnabled(true);
        this.jButtonArrancar.setEnabled(false);
        a1.Arrancar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonArrancarActionPerformed

    private void jButtonPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPararActionPerformed
        this.jButtonAcelerar.setEnabled(false);
        this.jButtonDecelerar.setEnabled(false);
        this.jButtonParar.setEnabled(false);
        this.jButtonArrancar.setEnabled(true);
        a1.Parar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonPararActionPerformed

    private void jButtonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEntrarActionPerformed
        a1.Entrar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonEntrarActionPerformed

    private void jButtonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcelerarActionPerformed
        a1.Acelerar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonAcelerarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        a1.Salir();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonDecelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDecelerarActionPerformed
        a1.Decelerar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonDecelerarActionPerformed

    private void jButtonRepostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepostarActionPerformed
        a1.Repostar();
        this.jLabelDatos.setText(a1.toString());
    }//GEN-LAST:event_jButtonRepostarActionPerformed

    private void jLabelDatosPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jLabelDatosPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelDatosPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Automovil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GUI_Automovil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcelerar;
    private javax.swing.JButton jButtonArrancar;
    private javax.swing.JButton jButtonDecelerar;
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JButton jButtonParar;
    private javax.swing.JButton jButtonRepostar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelDatos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
